"""Benchmark profile helpers."""

from turboquant.bench.external import (
    CommandSpec,
    KVSpec,
    assert_corpus_identity,
    build_llama_generation_command,
    build_llama_kld_base_command,
    build_llama_kld_command,
    build_llama_tokenize_command,
    build_llama_trajectory_command,
    corpus_identity,
    extra_engine_flags,
    parse_kld_metrics,
    parse_token_ids,
    parse_trajectory_jsonl,
    sglang_kv_pair,
    strip_engine_output,
    vllm_kv_dtype,
    write_corpus_sidecar,
)
from turboquant.bench.profile import (
    DeviceProfile,
    ModelProfile,
    RunPoint,
    RunProfile,
    SystemProfile,
    compare_run_profiles,
    parse_profile_text,
)

__all__ = [
    "DeviceProfile",
    "CommandSpec",
    "KVSpec",
    "ModelProfile",
    "RunPoint",
    "RunProfile",
    "SystemProfile",
    "assert_corpus_identity",
    "build_llama_generation_command",
    "build_llama_kld_base_command",
    "build_llama_kld_command",
    "build_llama_tokenize_command",
    "build_llama_trajectory_command",
    "compare_run_profiles",
    "corpus_identity",
    "extra_engine_flags",
    "parse_kld_metrics",
    "parse_token_ids",
    "parse_profile_text",
    "parse_trajectory_jsonl",
    "sglang_kv_pair",
    "strip_engine_output",
    "vllm_kv_dtype",
    "write_corpus_sidecar",
]
